### ISSUE TITLE
Remove JS from problem-results-partial

### ISSUE THREAD

**Issue by scajanus** [scajanus/moonboardsearch#15]
Since it's reloaded for every search, problem-results-partial should contain only necessary (i.e. changed) data, and the javascript should only be loaded once (as a static asset).

**Comment by timparkin** [comment]
Sounds good to me - I'll try to write it in functions too

**Comment by timparkin** [comment]
Done this - just checked in

**Comment by timparkin** [comment]
I forgot to do main.js but that's done now too
