### ISSUE TITLE
Move reset button below the search-moonboard

### ISSUE THREAD

**Issue by scajanus** [scajanus/moonboardsearch#17]
and maybe use a red button from bootstrap4 for it.

**Comment by timparkin** [comment]
temporarily stuck them in for debugging. They shouldn't really be necessary. I'll tie them into a get parameter so they only appear for ?debug=1

**Comment by scajanus** [comment]
I see -- let's still have a reset/clear for the removing clearing the clicked holds so you don't have to cycle through them to reset.

**Comment by timparkin** [comment]
Done and made the full  reset check for debug get parameter
