### ISSUE TITLE
Safari still caching (-> not updating) AJAX requests?

### ISSUE THREAD

**Issue by scajanus** [scajanus/moonboardsearch#18]

**Comment by timparkin** [comment]
Hmmm - no idea. How were you planning on making it sessionstorage free?

**Comment by scajanus** [comment]
Safari is very aggressive in using cached results, so something like this needs to be done: https://stackoverflow.com/questions/12506897/is-safari-on-ios-6-caching-ajax-results?rq=1

not sure if 'nocache' or 'no-cache' in the request parameters is not enough...

(Not) using sessionstorage should not have anything to do with this.

**Comment by scajanus** [comment]
> 
> 
> Hmmm - no idea. How were you planning on making it sessionstorage free?

Since all happens on a single page, javascript variables are persistent.

**Comment by timparkin** [comment]
I've added a @never_cache decorator to each of the page response functions.. Hopefully this will work. Committed just  now
